name: Tests

on: [ push, pull_request ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10" ]
        tox-env: ["mypy", "flake8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install tox
      - name: Run
        run: tox -e ${{ matrix.tox-env }}
